title: "Hume Texts Online"
description: "A permanent online resource for Hume scholars and students, including reliable texts of almost everything written by David Hume, and links to secondary material on the web."
baseurl: ""
permalink: /:title
version: 6
sass:
  style: "compressed"
